### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lin-China** [OmegaWeaponDev/OmegaNames#1]
Nice plugin and it helps me a lot!
It's good but...I'm afraid I found some bugs...
![image](https://user-images.githubusercontent.com/64890621/81203430-85f14900-8ffa-11ea-91be-cdf31dc65751.png)
Suffixes and chat messages are affected.
If you can solve this problem, he will be more perfect!

**Comment by OmegaWeaponDev** [comment]
This should now be fixed. Please update to version 1.0.4 on Spigot. 

Please reply here if you can confirm that the issue has been resolved.
