### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by rshuttle1337** [OmegaWeaponDev/OmegaNames#3]
Hi!

Love the plugin, been using is for ages now! 
However, I have recently been experiencing a memory leak on my server. I analysed a heap and it seems OmegaNames was behind it:
https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMC8xMS8xOC8tLWhlYXAtMjAyMC0xMS0xOF8yMS4yOS4wNy56aXAtMjEtNDEtMjMuanNvbi0t

Regards,
Robert

**Comment by OmegaWeaponDev** [comment]
Hi,

Thanks for reporting this. 

After looking into it, I believe I have now resolved the issue and have released version 1.1.15. Please update to this version and let me know if the issue continues. 

Thanks,
OmegaWeaponDev

**Comment by OmegaWeaponDev** [comment]
Hi,

It has been 1 week and I have not heard anything so I'm going to assume this is now resolved.

Thanks,
OmegaWeaponDev
